### ISSUE TITLE
Convert the paragraph id to class both in index.html file and styles.css file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#100]
Convert the paragraph id to class both in index.html file and styles.css file

**Comment by octosapien** [comment]
I would love to work on this .
Please assign me this issue .

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this . Please assign me this issue .

Sure, go ahead @octosapien
