### ISSUE TITLE
Convert the download button id to class both in index.html file and styles.css file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#101]
Convert the download button id to class both in index.html file and styles.css file

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204

**Comment by YandaSN** [comment]
Hi, can I be assigned to this please.

**Comment by YoshithaRathnayake** [comment]
> Hi, can I be assigned to this please.

I will assign you all, the one who has done it first, it will accepted and get merged! @Abhishekgupta204  @YandaSN
