### ISSUE TITLE
Create a new class for the img and replace it with the global css in the styles.css file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#102]
Create a new class for the img and replace it with the global css in the styles.css file

**Comment by octosapien** [comment]
I would love to work on this .
Please assign me this issue .

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this . Please assign me this issue .

Sure, go ahead @octosapien

**Comment by octosapien** [comment]
@YoshithaRathnayake 
It would help if you could elaborate a bit on what is meant by " replace it with the global css " ?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake It would help if you could elaborate a bit on what is meant by " replace it with the global css " ?

That means like we are adding some css to the html tags such as body, img, h1, h2. So they are called as adding css globally @octosapien

**Comment by sandilemnikathi** [comment]
Is this done yet, if not can I be assigned

**Comment by YoshithaRathnayake** [comment]
> Is this done yet, if not can I be assigned

You can work on this @sandilemnikathi

**Comment by codesmith25103** [comment]
can you assign me this?

**Comment by YoshithaRathnayake** [comment]
> can you assign me this?

Sure @codesmith25103

**Comment by bhavy2202** [comment]
can you assign me?

**Comment by YoshithaRathnayake** [comment]
> can you assign me?

Sure @bhavy2202
