### ISSUE TITLE
Increase the heading font size

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#106]
Increase the heading font size

**Comment by Yushmanth-reddy** [comment]
can you assign me this

**Comment by YoshithaRathnayake** [comment]
> can you assign me this

Sure, go ahead @Yushmanth-reddy

**Comment by iamAditya01** [comment]
can you assign me this one ? would be a pleasure to contribute to open source community

**Comment by YoshithaRathnayake** [comment]
Sure

**Comment by YoshithaRathnayake** [comment]
> I will assign you all, the one who has done it first, it will accepted and get merged! @Yushmanth-reddy @Arcturus22

Read this @iamAditya01

**Comment by iamAditya01** [comment]
arey dude where is the file ? where am i supposed to increase the god damn font !

**Comment by YoshithaRathnayake** [comment]
> arey dude where is the file ? where am i supposed to increase the god damn font !

You don't work on this @iamAditya01

**Comment by iamAditya01** [comment]
lmao ! kids these days

**Comment by iamAditya01** [comment]
lmao ! kids these days

**Comment by YoshithaRathnayake** [comment]
> lmao ! kids these days

Bla bla bla
