### ISSUE TITLE
Make the background blur of the paragraph

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#112]
Make the background blur of the paragraph

**Comment by YoshithaRathnayake** [comment]
> maintainer, please explain this issue again ?

Sure, you have to blur the background of the paragraph section. Simply add backdrop filter to blur property in css @Sathasivamthirumoorthi

**Comment by YoshithaRathnayake** [comment]
> maintainer, please explain this issue again ?

Shall I assign you @Sathasivamthirumoorthi

**Comment by octosapien** [comment]
I want to work on this issue .
Could you assign me this ?

**Comment by Sathasivamthirumoorthi** [comment]
yes

**Comment by YoshithaRathnayake** [comment]
> I want to work on this issue . Could you assign me this ?

Shall we give this chance to this new comer @octosapien

**Comment by YoshithaRathnayake** [comment]
> yes

Sure, go ahead @Sathasivamthirumoorthi

**Comment by YoshithaRathnayake** [comment]
> > > I want to work on this issue . Could you assign me this ?
> > 
> > 
> > Shall we give this chance to this new comer @octosapien
> 
> Sure .

Thanks @octosapien

**Comment by riddhitech** [comment]
Please assign me this issue.
