### ISSUE TITLE
Make the download button hover effect more attractive

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#113]
Make the download button hover effect more attractive

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204

**Comment by PriteshKiri** [comment]
Can you please assign this to me as well?

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged! @Abhishekgupta204  @PriteshKiri

**Comment by PriteshKiri** [comment]
I have made a PR kindly check and merge

**Comment by YoshithaRathnayake** [comment]
> I have made a PR kindly check and merge

A screenshot of the changes requested @PriteshKiri
