### ISSUE TITLE
Change the description little bit

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#114]
Change the description little bit

Hi, I am Yoshitha Rathnayake. This is the Calculator App that I made using Python Programming Language. You can download it by clicking the below "Download" button. It's saying there are viruses, but don't worry they are lies.

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204
