### ISSUE TITLE
Make the download button text uppercase

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#115]
Make the download button text uppercase

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204

**Comment by riddhitech** [comment]
Please assign me this issue.
