### ISSUE TITLE
Change the link in the readme.md file to redirect the official website

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#116]
Change the link in the readme.md file to redirect the official website

![image](https://user-images.githubusercontent.com/97069900/197588673-53cd6397-7e5c-45af-8f8f-91a4e83291e9.png)

Add this link = calculator.yoshitha.tk

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
May I work on this issue?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake May I work on this issue?

Sure, go ahead @Arcturus22
