### ISSUE TITLE
Add the calculator logo to the features section in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#117]
Add the calculator logo to the features section in the readme.md file

**Comment by Sathasivamthirumoorthi** [comment]
can you please assign this to me

**Comment by Sathasivamthirumoorthi** [comment]
![Screenshot from 2022-10-24 23-59-12](https://user-images.githubusercontent.com/97246670/197599167-153f59b4-f690-40d4-8e1d-a273928b03a6.png)

**Comment by Sathasivamthirumoorthi** [comment]
Is this okay @YoshithaRathnayake

**Comment by Sathasivamthirumoorthi** [comment]
hey @YoshithaRathnayake  i have created PR , please check

**Comment by YoshithaRathnayake** [comment]
> hey @YoshithaRathnayake i have created PR , please check

Sure @Sathasivamthirumoorthi

**Comment by YoshithaRathnayake** [comment]
I couldn't found any pr regarding to this issue can you add this as the src and create a new pr @Sathasivamthirumoorthi 

src - assets/img/CALCULATOR.png

**Comment by Arunkumar-60** [comment]
assign me this task

**Comment by YoshithaRathnayake** [comment]
> assign me this task

Sure @Arunkumar-60

**Comment by YoshithaRathnayake** [comment]
> I couldn't found any pr regarding to this issue can you add this as the src and create a new pr @Sathasivamthirumoorthi
> 
> src - assets/img/CALCULATOR.png

Do this @Arunkumar-60
