### ISSUE TITLE
Remove the dash in the Used Programming Languages description

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#118]
Remove the dash in the Used Programming Languages description

![image](https://user-images.githubusercontent.com/97069900/197589561-e3694c58-04b8-4398-ad2d-88ceeefeba4a.png)

Add the sentence like this = Used Programming Languages (HTML, CSS, BOOTSTRAP, PYTHON)

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake  I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204

**Comment by YandaSN** [comment]
Hi, could I work on this, I would like to be assigned

**Comment by YoshithaRathnayake** [comment]
> Hi, could I work on this, I would like to be assigned

I will assign you all, the one who has done it first, it will accepted and get merged! @YandaSN  @Abhishekgupta204

**Comment by Roxie2003** [comment]
Can you assign me this?

**Comment by YoshithaRathnayake** [comment]
> Can you assign me this?

Sure, go ahead @Roxie2003
