### ISSUE TITLE
Add python logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#119]
Add python logo to the readme.md file  

![image](https://user-images.githubusercontent.com/97069900/197590644-c7d1ddea-315e-4d18-94c0-00bce04053a9.png)

**Comment by HluvukoMavundza** [comment]
can i be assigned this issue

**Comment by YoshithaRathnayake** [comment]
> can i be assigned this issue

Sure, go ahead @HluvukoMavundza
