### ISSUE TITLE
Change the last sentence of the Contributing Section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#120]
Change the last sentence of the Contributing Section

![image](https://user-images.githubusercontent.com/97069900/197590831-c46ec027-b77b-47d9-8f1c-c9371fb381c0.png)

Add this sentence = The Pull Requests will be reviewed, accepted and merged accordingly.

**Comment by Sathasivamthirumoorthi** [comment]
can i assign this to me please

**Comment by YoshithaRathnayake** [comment]
> can you assign this to me please!

Sure, go ahead @Sathasivamthirumoorthi

**Comment by Arcturus22** [comment]
@YoshithaRathnayake
I want to resolve this issue. Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I want to resolve this issue. Please assign me this issue.

Shall we give this chance to this new comer @Arcturus22. If he didn't work on this, I will assign you ok?

**Comment by Arcturus22** [comment]
> > @YoshithaRathnayake I want to resolve this issue. Please assign me this issue.
> 
> Shall we give this chance to this new comer @Arcturus22. If he didn't work on this, I will assign you ok?

Alright, I don't mind.

**Comment by YoshithaRathnayake** [comment]
> > > @YoshithaRathnayake I want to resolve this issue. Please assign me this issue.
> > 
> > 
> > Shall we give this chance to this new comer @Arcturus22. If he didn't work on this, I will assign you ok?
> 
> Alright, I don't mind.

Thanks @Arcturus22
