### ISSUE TITLE
Remove the (ME) part from the first sentence in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#121]
Remove the (ME) part from the first sentence in the readme.md file

![image](https://user-images.githubusercontent.com/97069900/197591197-8a8bda4d-8018-4d8c-955e-896956b71406.png)

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
I want to resolve this issue. Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I want to resolve this issue. Please assign me this issue.

Sure, go ahead @Arcturus22
