### ISSUE TITLE
Blur more the paragraph background

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#136]
Blur more the paragraph background. Add 50px as the blur rate

**Comment by tarunvashishth** [comment]
I would like to work on this.

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this.

Sure, go ahead @tarunvashishth

**Comment by YandaSN** [comment]
Hi there, 
could I also add to this please.

**Comment by YoshithaRathnayake** [comment]
> Hi there, could I also add to this please.

I will assign you all, the one who has done it first, it will accepted and get merged! @YandaSN  @tarunvashishth

**Comment by sandilemnikathi** [comment]
@YoshithaRathnayake Please assign me
