### ISSUE TITLE
Change the title of the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#137]
Change the title of the readme.md file as follows

![image](https://user-images.githubusercontent.com/97069900/197768522-dba9e4a3-1995-4f1b-96e0-70741123f92d.png)

**Comment by Mercysticks** [comment]
please assign this to me 
Let me work on it.

**Comment by YoshithaRathnayake** [comment]
> please assign this to me Let me work on it.

Sure, go ahead @Mercysticks

**Comment by PriteshKiri** [comment]
Can you please assign this to me as well

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged! @Mercysticks  @PriteshKiri

**Comment by PriteshKiri** [comment]
Have made a PR for this issue. Kindly check and merge.
