### ISSUE TITLE
Decrease the size of the image

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#14]
Decrease the size of the image

**Comment by Shruti1998-mona** [comment]
Can i do this issue?

**Comment by YoshithaRathnayake** [comment]
> Can i do this issue?

Sure, go ahead @Shruti1998-mona

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I am willing to work on this issue.Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I am willing to work on this issue.Please assign this issue to me.

Sure, go ahead @Abhishekgupta204
