### ISSUE TITLE
Add a beautiful scroll bar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#144]
Add a beautiful scroll bar

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.
Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign me this issue.

Sure, go ahead @Abhishekgupta204

**Comment by HluvukoMavundza** [comment]
can i also work on this issue

**Comment by LordMahir** [comment]
Please assign it to me

**Comment by YoshithaRathnayake** [comment]
> Please assign it to me

Sure @LordMahir

**Comment by ShivPandey5677** [comment]
Can you  please assign it to me i have previously worked on similar issue in other repository

**Comment by YoshithaRathnayake** [comment]
> Can you please assign it to me i have previously worked on similar issue in other repository

Sure @ShivPandey5677
