### ISSUE TITLE
Download button icon is missing

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#15]
Add the download button icon properly

**Comment by octosapien** [comment]
I would really like to work on this .
Please assign this issue to me .

**Comment by yf151290** [comment]
Can you Assign this to me

**Comment by YoshithaRathnayake** [comment]
> Can you Assign this to me

Sure, go ahead @yf151290

**Comment by YoshithaRathnayake** [comment]
> I would really like to work on this . Please assign this issue to me .

@octosapien I assigned @yf151290 bcs you have two assigned issues ok?

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I am willing to work on this issue please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I am willing to work on this issue please assign this issue to me.


Sure, go ahead @Abhishekgupta204
