### ISSUE TITLE
Create a interactive navigation bar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#150]
Create a interactive navigation bar

**Comment by Mayureshkaulwar** [comment]
please assign to me

**Comment by YoshithaRathnayake** [comment]
> please assign to me

Are you sure to handle this. I want a perfect navbar. Can you do this? @Mayureshkaulwar

**Comment by Arunkumar-60** [comment]
please assign me the task

**Comment by YoshithaRathnayake** [comment]
> please assign me the task

Sure @Arunkumar-60
