### ISSUE TITLE
Add the YAML logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#151]
Add the YAML logo to the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198270706-dd72780f-dfa3-46cd-b149-e3f4c664fce1.png)

**Comment by zmusaddique** [comment]
Hey @YoshithaRathnayake!

I would like to work on this

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake!
> 
> I would like to work on this

Sure, go ahead @zmusaddique

**Comment by Arunkumar-60** [comment]
please assign me the task

**Comment by YoshithaRathnayake** [comment]
> please assign me the task

sure

**Comment by zmusaddique** [comment]
![image](https://user-images.githubusercontent.com/84737749/198533697-a23b07ac-b203-4986-89c2-4d10c67a7e53.png)

This is how it looks after resolving the conflict

**Comment by zmusaddique** [comment]
Are you satisfied with it?

**Comment by YoshithaRathnayake** [comment]
> Are you satisfied with it?

Decrease the size of the icon @zmusaddique
