### ISSUE TITLE
Add the javascript logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#152]
Add the javascript logo to the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198270706-dd72780f-dfa3-46cd-b149-e3f4c664fce1.png)

**Comment by kheersagar** [comment]
please assign this task to me

**Comment by YoshithaRathnayake** [comment]
> please assign this task to me

Sure, go ahead @kheersagar

**Comment by Arunkumar-60** [comment]
please assign me the task
