### ISSUE TITLE
Add a background image

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#16]
Add this background image to the site

![Background Image](https://user-images.githubusercontent.com/97069900/196757789-601bf265-90ad-4b02-bf37-a3d3f63ecef5.jpg)

**Comment by rishabhknowss** [comment]
please assign me this issue

**Comment by ankit060801** [comment]
sir please assign me to this task

**Comment by YoshithaRathnayake** [comment]
> sir please assign me to this task

Sure, go ahead @ankit060801

**Comment by YoshithaRathnayake** [comment]
> sir please assign me to this task

Bro @ankit060801 don't tell me sir 😂😊. Tell me brother that's good for me 😊

**Comment by ankit060801** [comment]
ok bro @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> ok bro @YoshithaRathnayake

Nice @ankit060801

**Comment by bhavy2202** [comment]
Hey, is this issue still open?

**Comment by YoshithaRathnayake** [comment]
Yes @bhavy2202

**Comment by bhavy2202** [comment]
Please assign me

**Comment by YoshithaRathnayake** [comment]
> Please assign me

Sure, go ahead @bhavy2202
