### ISSUE TITLE
Add javascript to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#163]
Add javascript to the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198659524-69db5359-de4e-43c8-b7c9-d2313a63eeb5.png)

**Comment by Zweak** [comment]
assign me

**Comment by YoshithaRathnayake** [comment]
> assign me

Sure, go ahead @Zweak

**Comment by Blazeleo** [comment]
Hi i'm done.

**Comment by YoshithaRathnayake** [comment]
> Hi i'm done.

You are not assigned @Blazeleo
