### ISSUE TITLE
Change the sentence in readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#166]
Change the sentence in readme.md file as `Used Programming Languages (HTML, CSS, and BOOTSTRAP)`

![image](https://user-images.githubusercontent.com/97069900/198675082-2fa419d8-f4d0-4af6-b4d5-37756b7b7a0d.png)

**Comment by KanjiZain** [comment]
Please assign it to me @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Please assign it to me @YoshithaRathnayake

Sure, go ahead @KanjiZain
