### ISSUE TITLE
Add Yaml for the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#168]
Add Yaml for the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198676036-62ab6215-fa28-498a-a9d6-b6d111a135bb.png)

**Comment by codesmith25103** [comment]
Can you assign me this?

**Comment by YoshithaRathnayake** [comment]
> Can you assign me this?

Sure, go ahead @codesmith25103

**Comment by Roxie2003** [comment]
Can I work on it?

**Comment by YoshithaRathnayake** [comment]
> Can I work on it?

Sure @Roxie2003
