### ISSUE TITLE
Change the topic font style

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#17]
Change the topic font style to `EDO` font

**Comment by rishabhknowss** [comment]
please assign me this issue

**Comment by YoshithaRathnayake** [comment]
> please assign me this issue

Sure, go ahead @rishabhknowss

**Comment by Vishesh-Vijay** [comment]
pls assign this to me

**Comment by YoshithaRathnayake** [comment]
> pls assign this to me

Sure go ahead @Vishesh-Vijay

**Comment by kashish0604** [comment]
hey @YoshithaRathnayake can u assign this issue to me i can work on it

**Comment by YoshithaRathnayake** [comment]
> hey @YoshithaRathnayake can u assign this issue to me i can work on it

Sure, go ahead @kashish0604

**Comment by bhavy2202** [comment]
Please assign me if this is still open.

**Comment by YoshithaRathnayake** [comment]
> Please assign me if this is still open.

I will assign both of you and one who has opened the pr first, I will accept his/her pr and I will merge. @kashish0604 @bhavy2202
