### ISSUE TITLE
Repositioning visitor counter

### ISSUE THREAD

**Issue by divya-nshi** [YoshithaRathnayake/CALCULATOR-WEBSITE#173]
The visitor counter is not looking good at the corner. Aligning it with the description box in the center would give it a classy look.
i would like to solve this. could u please label it under hacktoberfest if u think this is needed.
![image](https://user-images.githubusercontent.com/96721993/198872845-a9e26036-3ac2-443f-8405-daeddd2c56ab.png)

**Comment by YoshithaRathnayake** [comment]
Nice! go ahead @divya-nshi
