### ISSUE TITLE
Increase the margin between the download button and visitors counter

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#175]
Increase the margin between the download button and visitors counter

**Comment by JanitaRiyaz** [comment]
i wanna do this. Plz assign this to me.

**Comment by YoshithaRathnayake** [comment]
> i wanna do this. Plz assign this to me.

Sure, go ahead @JanitaRiyaz

**Comment by JanitaRiyaz** [comment]
Your website is really awsome... The UI is really great.🙂

**Comment by YoshithaRathnayake** [comment]
> Your website is really awsome... The UI is really great.🙂

Thanks @JanitaRiyaz
