### ISSUE TITLE
The main heading's font style has been changed

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#180]
The main heading's font style has been changed. Change it to edo font

**Comment by msabil443** [comment]
Hey @YoshithaRathnayake I can solve this issue

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake I can solve this issue

Yes sure go ahead @msabil443

**Comment by Vishu-uut** [comment]
Can I do it?

**Comment by YoshithaRathnayake** [comment]
> Can I do it?

Sure I found the error its only working on chrome, the font style is not working in the brave browser, so fix that @msabil443 @Vishu-uut

**Comment by YoshithaRathnayake** [comment]
Fixed
