### ISSUE TITLE
Customize the nav bar to a beautiful design

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#182]
Customize the nav bar to a beautiful design

**Comment by aksy2512** [comment]
Can I work on this issue

**Comment by YoshithaRathnayake** [comment]
> Hi! Can you please assign this issue to me

Sure @aksy2512

**Comment by aksy2512** [comment]
@YoshithaRathnayake I don't how my PR got closed so I have created a new Pull request for the same. I apologize for the inconvenience
