### ISSUE TITLE
Increase the margin of the paragraph

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#19]
Increase the margin of the paragraph

**Comment by YoshithaRathnayake** [comment]
> please assign me this issue

shall we give this chance to another bcs you have two assigned issues after that I will check and assign you ok? @rishabhknowss

**Comment by YoshithaRathnayake** [comment]
> sir please assign to me

Sure, go ahead @ankit060801

**Comment by bhavy2202** [comment]
Please assign me if this is still open

**Comment by YoshithaRathnayake** [comment]
> Please assign me if this is still open

Sure, go ahead @bhavy2202

**Comment by bhavy2202** [comment]
Can you elaborate a bit on the issue? Should I increase the padding or margin of the whole paragraph box?

**Comment by YoshithaRathnayake** [comment]
> Can you elaborate a bit on the issue? Should I increase the padding or margin of the whole paragraph box?

Both padding and margin @bhavy2202

**Comment by YoshithaRathnayake** [comment]
I will assign all of you and one who has opened the pr first, I will accept his/her pr and I will merge. @rishabhknowss @ankit060801 @Vishesh-Vijay @bhavy2202
