### ISSUE TITLE
Add the topic

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#2]
Add the topic

**Comment by yoshitha2008** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @yoshitha2008

**Comment by Sayli6242** [comment]
What is this issue? I cant get it?

**Comment by YoshithaRathnayake** [comment]
> What is this issue? I cant get it?

sure

**Comment by YoshithaRathnayake** [comment]
> What is this issue? I cant get it?

Adding the CALCULATOR topic

**Comment by Sayli6242** [comment]
> > What is this issue? I cant get it?
> 
> Adding the CALCULATOR topic

can i add python calculator code

**Comment by YoshithaRathnayake** [comment]
> > > What is this issue? I cant get it?
> > 
> > 
> > Adding the CALCULATOR topic
> 
> can i add python calculator code

nope topic only for website

**Comment by yoshitha-hack** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @yoshitha-hack
