### ISSUE TITLE
Align the image to center

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#20]
Align the image to center

**Comment by JoydeepMallick** [comment]
I would like to work on this issue. Is it the calculator image in index.html to be centered?

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this issue. Is it the calculator image in index.html to be centered?

Sure, go ahead @JoydeepMallick . You have to center the cal image

**Comment by YoshithaRathnayake** [comment]
Just simply put a center html tag for the img tag @JoydeepMallick

**Comment by JoydeepMallick** [comment]
ok working on it.

**Comment by YoshithaRathnayake** [comment]
> ok working on it.

Sure thanks

**Comment by JoydeepMallick** [comment]
I have made the PR, please check it out.
