### ISSUE TITLE
Decrease the font weight of the paragraph little bit

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#22]
Decrease the font weight of the paragraph little bit

**Comment by octosapien** [comment]
I would like to work on this issue .
Please assign this issue to me .

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this issue . Please assign this issue to me .

Sure, go ahead @octosapien

**Comment by charandevreddy** [comment]
can you assign me this?

**Comment by octosapien** [comment]
Thanks for assigning.
I am working on this issue.
