### ISSUE TITLE
Change the interface image of the calculator

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#231]
Change the interface image of the calculator

Add this image

![image](https://user-images.githubusercontent.com/97069900/210254461-4e33166d-0281-438a-8309-e1b2b479c939.png)

**Comment by YoshithaRathnayake** [comment]
Can you work on this? @Prasadkpd

**Comment by Prasadkpd** [comment]
Sure I will work on this

**Comment by YoshithaRathnayake** [comment]
> Sure I will work on this

Thanks
