### ISSUE TITLE
Align the calculator interface image center

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#232]
Align the calculator interface image center

![image](https://user-images.githubusercontent.com/97069900/210255670-47d20949-27a5-43d1-84fb-769730214da1.png)

**Comment by Devemmy01** [comment]
Can I work on this?

**Comment by YoshithaRathnayake** [comment]
> Can I work on this?

Yes, sure @Devemmy01

**Comment by Devemmy01** [comment]
I'm sorry i can't find the app file and I cant work with python

**Comment by YoshithaRathnayake** [comment]
> I'm sorry i can't find the app file and I cant work with python

No need of python you have to center the image in the readme.md file @Devemmy01

**Comment by iamravi-prakash** [comment]
hey is still open? can i work on this?

**Comment by Prasadkpd** [comment]
@YoshithaRathnayake Is this still open, can I work on this?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Is this still open, can I work on this?

Sure go ahead @Prasadkpd
