### ISSUE TITLE
Align the download button to center

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#27]
Align the download button to center

**Comment by Anish-Sarawgi** [comment]
I Want to work on this issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I Want to work on this issue.

Sure, go ahead @Anish-Sarawgi

**Comment by DivyanshVinayak23** [comment]
Hi can I also work on this?

**Comment by Vishesh-Vijay** [comment]
pls assign this to me

**Comment by Anish-Sarawgi** [comment]
Hey @YoshithaRathnayake,
I mistakely clicked on the unassign button, please re-assign this to me. Also i have sent a PR, please look into the changes.

Thankyou!

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake, I mistakely clicked on the unassign button, please re-assign this to me. Also i have sent a PR, please look into the changes.
> 
> Thankyou!

Sure, Merged! Thank you @Anish-Sarawgi
