### ISSUE TITLE
There are two calculator images

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#30]
Remove the small calculator image

**Comment by DivyanshVinayak23** [comment]
Hi can I work on this?

**Comment by pratyushkr11** [comment]
Hello @YoshithaRathnayake please assign me this issue. I would like to work on this.

**Comment by YoshithaRathnayake** [comment]
> Remove the small calculator image

Sure, go ahead @DivyanshVinayak23
