### ISSUE TITLE
Optimize the mobile view for the calculator-website

### ISSUE THREAD

**Issue by ShreyasSahoo** [YoshithaRathnayake/CALCULATOR-WEBSITE#35]
Optimize the mobile view for the calculator-website

**Comment by ShreyasSahoo** [comment]
@YoshithaRathnayake , can i work on this issue ? Please assign hacktoberfest-accepted label to the issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake , can i work on this issue ? Please assign hacktoberfest-accepted label to the issue.

Sure, good watch @ShreyasSahoo
