### ISSUE TITLE
Add a new design to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#42]
Add a new design to the readme.md file

**Comment by Arcturus22** [comment]
I would love to work on this. Please assign me this issue.

**Comment by siddhesh-desai** [comment]
Hello, I would like to solve this. Please assign me to this issue.  Thankyou.

**Comment by SohamG934** [comment]
Hello @YoshithaRathnayake! I would like to work on this issue. Can you please assign it to me?

**Comment by YoshithaRathnayake** [comment]
> Hello @YoshithaRathnayake! I would like to work on this issue. Can you please assign it to me?

Sure, go ahead @SohamG934

**Comment by Abhishekgupta204** [comment]
Please assign this issue to me.  I would love to work on this

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake  please assign this issue to me.I would love to work on this.

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this. Please assign me this issue.

I will assign you @Arcturus22 can you work on this?

**Comment by Arcturus22** [comment]
> > I would love to work on this. Please assign me this issue.
> 
> I will assign you @Arcturus22 can you work on this?

Yes, Gladly.
Will it be possible for you to tell me what more I should include in it?
@YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> > > I would love to work on this. Please assign me this issue.
> > 
> > 
> > I will assign you @Arcturus22 can you work on this?
> 
> Yes, Gladly. Will it be possible for you to tell me what more I should include in it? @YoshithaRathnayake

You can do it like this https://www.github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE see the readme.md file of this repository and do it like it @Arcturus22
