### ISSUE TITLE
big-calculator class of the img tag is missing

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#44]
big-calculator class of the img tag is missing. Add the big-calculator class to the img tag.

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
I would like to resolve this issue.Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would like to resolve this issue.Please assign me this issue.

Sure, go ahead @Arcturus22
