### ISSUE TITLE
Wrap the download button tag with div tag with an id called button

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#45]
Wrap the download button tag with div tag with an id called button

**Comment by Arcturus22** [comment]
I would really love to work on this issue.
Please @YoshithaRathnayake assign me this issue.

**Comment by YoshithaRathnayake** [comment]
> I would really love to work on this issue. Please @YoshithaRathnayake assign me this issue.

Sure, go ahead @Arcturus22

**Comment by Tanucode** [comment]
I would like to work on this..can you please assign me this?

**Comment by YoshithaRathnayake** [comment]
Assigned @Tanucode bcs you have an assigned issue @Arcturus22

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this..can you please assign me this?

Go ahed @Tanucode

**Comment by Pravar25** [comment]
I would like to work on it, can you please assign me this?

**Comment by Arcturus22** [comment]
> Assigned @Tanucode bcs you have an assigned issue @Arcturus22

Sir, I was really looking forward to resolving this issue. Would it be possible for you to reassign me this issue?

**Comment by YoshithaRathnayake** [comment]
> > Assigned @Tanucode bcs you have an assigned issue @Arcturus22
> > @YoshithaRathnayake
> > Sir, I was really looking forward to resolving this issue. Would it be possible for you to reassign me this issue?

??? Did you say anything @Arcturus22

**Comment by Arcturus22** [comment]
I was asking if it would be possible for you to assign this issue to me also (or reassign me). I was looking forward to contributing to it.
@YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> I was asking if it would be possible for you to assign this issue to me also (or reassign me). I was looking forward to contributing to it. @YoshithaRathnayake

Ok then I will assign you to this issue @Arcturus22
