### ISSUE TITLE
Remove the styles add for text-center class

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#46]
The class put for title as text-center is an bootstrap class that centers the text. Someone have put that class in styles.css file and added some custom css. Add a new class called title. Then replace that .title class with the .text-center class in styles.css

**Comment by octosapien** [comment]
I would love to work on this issue @YoshithaRathnayake .
Please assign me this issue .

**Comment by ankitkumar0622** [comment]
Hi , can you please assign me this task.

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this issue @YoshithaRathnayake . Please assign me this issue .

Sure, go ahead @octosapien

**Comment by YoshithaRathnayake** [comment]
> Hi , can you please assign me this task.

I will assign both of you and one who has opened the pr first, I will accept his/her pr and I will merge. @octosapien @ankitkumar0622

**Comment by octosapien** [comment]
@YoshithaRathnayake 
I had been assigned this issue .
And as I recall , this issue had been resolved by my Pull Request numbered #50 , which got merged .
However , this issue was not closed after being resolved by that same Pull Request .

The code no longer has this issue , but the issue is remains to be closed .

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I had been assigned this issue . And as I recall , this issue had been resolved by my Pull Request numbered #50 , which got merged . However , this issue was not closed after being resolved by that same Pull Request .
> 
> The code no longer has this issue , but the issue remains to be closed .

Oh sorry, I didn't see it. Thanks for reminding it to me @octosapien
