### ISSUE TITLE
Give the paragraph a faint grey background that distinguishes its contents from the rest of the page .

### ISSUE THREAD

**Issue by octosapien** [YoshithaRathnayake/CALCULATOR-WEBSITE#53]
The paragraph would be better readable and more distinguishable form the rest of the page if it had a slightly grey background and occupied a certain fraction of the page-width . 

This is how it would look...
![image](https://user-images.githubusercontent.com/114580332/197349926-6d7a568a-a13a-4e5f-8ae7-6839eb0433b2.png)

I would love to work on this .
Please assign me this issue .

**Comment by octosapien** [comment]
I would love to work on this .
Please assign me this issue .

**Comment by Tanucode** [comment]
can you assign this issue to me ?

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this . Please assign me this issue @YoshithaRathnayake

Sure, go ahead @octosapien
