### ISSUE TITLE
To fix the icon inside the download button and remove the other download button.

### ISSUE THREAD

**Issue by Abhishekgupta204** [YoshithaRathnayake/CALCULATOR-WEBSITE#56]
There are two download buttons on the website.It would be better if the icon inside one button was fixed and the other button was removed.
I would like to work on this issue.
Please assign this issue to me.

**Comment by Abhishekgupta204** [comment]
I would like to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204
