### ISSUE TITLE
Remove the .big-calculator class from styles.css file and from index.html file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#58]
.big-calculator class is no need for this site bcs I want to reduce the calculator image size. So remove the .big-calculator class from styles.css file and from index.html file

**Comment by kashish0604** [comment]
Hey @YoshithaRathnayake can you assign this issue to me i can work on it

**Comment by ShivPandey5677** [comment]
can you assign this issue to me
@YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake can you assign this issue to me i can work on it

Sure, go ahead @kashish0604

**Comment by YoshithaRathnayake** [comment]
> can you assign this issue to me @YoshithaRathnayake

I will assign both of you and one who has opened the pr first, I will accept his/her pr and I will merge. @kashish0604 @ShivPandey5677

**Comment by kashish0604** [comment]
hey @YoshithaRathnayake Done kindly check the PR

**Comment by YoshithaRathnayake** [comment]
> hey @YoshithaRathnayake Done kindly check the PR

Merged! @kashish0604
