### ISSUE TITLE
Add bg image

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#6]
Add bg image

**Comment by yoshitha2008** [comment]
shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> shall I work on this?

Sure, go ahead @yoshitha2008

**Comment by yoshitha-hack** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure, go ahead @yoshitha-hack
