### ISSUE TITLE
`Clone your forked repository` section and description are sticked together

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#60]
**Describe the bug**
`Clone your forked repository` section and description are sticked together

**To Reproduce**
1. Go to 'Readme.md file'
3. Scroll down to 'Clone your forked repository'

**Expected behavior**
Click the end of the Clone your forked repository title and hit enter

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/197317393-43f6f74a-75b1-4114-aa1b-836aebf975c1.png)

**Are you working on it?**
No

**Comment by Arcturus22** [comment]
Please assign me this.I would work on this.
 @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Please assign me this.I would work on this. @YoshithaRathnayake

Sure, go ahead @Arcturus22
