### ISSUE TITLE
Remove the "| YOSHITHA" part from the heading

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#68]
Remove the "| YOSHITHA" part from the heading

**Comment by JP109** [comment]
I would like to work on this issue.

**Comment by YoshithaRathnayake** [comment]
> I would like to work on this issue.

Sure, go ahead @JP109

**Comment by iamrahul25** [comment]
Can you please assign this issue to me.

**Comment by the3plet** [comment]
i would like to fix this issue assign me

**Comment by YoshithaRathnayake** [comment]
> i would like to fix this issue assign me

Sure, go ahead @the3plet

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged! @iamrahul25 @the3plet

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I would love to work on this issue.Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue.Please assign this issue to me.

Sure @Abhishekgupta204

**Comment by theotsuaneng** [comment]
Hi @YoshithaRathnayake can I please be assigned to this

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake can I please be assigned to this

Sorry a pr has already opened try another issue in this repo of in https://www.github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE @theotsuaneng
