### ISSUE TITLE
Bold the heading

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#69]
Bold the heading

**Comment by Pragya2056** [comment]
Please assign me

**Comment by YoshithaRathnayake** [comment]
> Please assign me

Sure, go ahead @Pragya2056

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake  I would like to work on this issue.
Please assign this issue to me.
