### ISSUE TITLE
Italic the heading

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#70]
Italic the heading

**Comment by Pragya2056** [comment]
Please assign me

**Comment by JP109** [comment]
Hi, I'd like to work on this issue!

**Comment by YoshithaRathnayake** [comment]
I will assign you all to this issue, the one who has opened the PR first, will accepted and merged by me @Pragya2056 @JP109
