### ISSUE TITLE
Reduce the background color of the paragraph

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#71]
Reduce the background color of the paragraph

**Comment by Pragya2056** [comment]
Please state what kind of reduction and assign me!!

**Comment by JP109** [comment]
Hi, I'd like to work on this issue!

**Comment by YoshithaRathnayake** [comment]
I will assign you all to this issue, the one who has opened the PR first, will accepted and merged by me @Pragya2056 @JP109

**Comment by Pragya2056** [comment]
@YoshithaRathnayake 
Color reduction to lighter ?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Color reduction to lighter ?

Yes @Pragya2056

**Comment by Pragya2056** [comment]
Okay!! Coming right up.

**Comment by the3plet** [comment]
please assign me

**Comment by octosapien** [comment]
I want to work on this.
Please assign me this issue .

**Comment by octosapien** [comment]
@YoshithaRathnayake
I wan to work on this issue.
Please assign me.

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged!
