### ISSUE TITLE
To add a hover effect on the download button

### ISSUE THREAD

**Issue by Abhishekgupta204** [YoshithaRathnayake/CALCULATOR-WEBSITE#78]
Add hover effect to the download button.
@YoshithaRathnayake  I would love to work on this issue.
Please assign this issue to me.

**Comment by Abhishekgupta204** [comment]
I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204
