### ISSUE TITLE
Change the title of this page to CALCULATOR | YOSHITHA

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#80]
Change the title of this page to CALCULATOR | YOSHITHA

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake  I would love to work on this issue.
Please assign this issue to me.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would love to work on this issue. Please assign this issue to me.

Sure, go ahead @Abhishekgupta204
