### ISSUE TITLE
Remove the bold from font-style property in .title class in styles.css file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#81]
Remove the bold from font-style property in .title class in styles.css file bcs if it is there it will become an error.

![image](https://user-images.githubusercontent.com/97069900/197403440-a68cc595-58c3-4784-96ef-5584b38cd45e.png)

**Comment by Tanucode** [comment]
can you assign me this?

**Comment by YoshithaRathnayake** [comment]
> can you assign me this?

Sure, go ahead @Tanucode

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
I want to work on this issue. Please assign me this issue.

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I am willing to work on this issue.
Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged! @ @

**Comment by YoshithaRathnayake** [comment]
> I will assign you all, the one who has done it first, it will accepted and get merged! @Tanucode  @Abhishekgupta204
