### ISSUE TITLE
Bold the main heading

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#82]
Bold the main heading

**Comment by Tanucode** [comment]
can you assign me this?

**Comment by YoshithaRathnayake** [comment]
> can you assign me this?

Sure, go ahead @Tanucode

**Comment by Arcturus22** [comment]
Please assign me this issue @YoshithaRathnayake

**Comment by Sanoj-DivJay** [comment]
can you assign me?

**Comment by atharbeginner** [comment]
Hello @YoshithaRathnayake, an you assign me this issue ?

**Comment by Abhishekgupta204** [comment]
@YoshithaRathnayake I am willing to work on this issue.
Please assign me this issue.

**Comment by YoshithaRathnayake** [comment]
I will assign you all, the one who has done it first, it will accepted and get merged!
