### ISSUE TITLE
Make the title margin 10px to 10vh

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/CALCULATOR-WEBSITE#83]
Make the title margin 10px to 10vh

![image](https://user-images.githubusercontent.com/97069900/197403679-cb45359c-7266-4310-a3a5-0fa09f9739f2.png)

**Comment by codesmith25103** [comment]
I want to change it. Can you please assign me this?

**Comment by YoshithaRathnayake** [comment]
> I want to change it. Can you please assign me this?

Sure, go ahead @codesmith25103
