### ISSUE TITLE
The page heading is not visible beacuse of being similar in color to the background image .

### ISSUE THREAD

**Issue by octosapien** [YoshithaRathnayake/CALCULATOR-WEBSITE#98]
The page heading is not visible beacuse of being similar in color to the background image .
The heading could be made to stand out from the background through changes to the CSS file.

Before the change ...
![image](https://user-images.githubusercontent.com/114580332/197548177-b53b128c-18aa-4159-95ca-6083201cf1e3.png)

After the change...
![image](https://user-images.githubusercontent.com/114580332/197548522-f0912628-60c9-48f5-9910-94d2c2e2fb3f.png)

**Comment by YoshithaRathnayake** [comment]
> I would love to work on this . Please assign me this issue .

Sure, go ahead @octosapien
